#!/bin/env python3
import fm
import time
import traceback
import sys

def main():
    fm.syncmail.sync()

import argparse
parser = argparse.ArgumentParser(description="sync mail")
parser.add_argument('-l', '--loop', help="loop", action='store_true')
parser.add_argument('--rebuild-db', help="rebuild db", action='store_true')


args = parser.parse_args()

if args.rebuild_db:
    fm.syncmail.rebuild_db()
    sys.exit(0)

if args.loop:
    while True:
        t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

        main()

        time.sleep(60)
else:
    main()
