#!/bin/env python3
import fm
import time
import traceback
import sys

def main():
    fm.syncmail.sync()

import argparse
parser = argparse.ArgumentParser(description="sync mail")
parser.add_argument('-l', '--loop', help="loop", action='store_true')
parser.add_argument('--rebuild-db', help="rebuild db", action='store_true')
parser.add_argument('--refresh-class', help="class", action='store_true')
parser.add_argument('-i', '--input', help="input one mail")


args = parser.parse_args()

if args.input:
    fm.syncmail.input(args.input)
    sys.exit(0)


if args.rebuild_db:
    fm.syncmail.Rebuild()
    sys.exit(0)

if args.refresh_class:
    fm.syncmail.refresh_class()
    sys.exit(0)

if args.loop:
    while True:
        t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

        main()

        time.sleep(60)
else:
    main()
